# Role for the MJS controller with permissions to interact with the Kubernetes cluster.
# Copyright 2024 The MathWorks, Inc.
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "resources.controllerRole" . }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "secrets"]
  verbs: ["create", "get", "list", "delete", "update"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "delete", "update"]