# Config file for the MJS controller.
# Copyright 2024-2026 The MathWorks, Inc.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resources.controllerConfigMap" . }}
data:
  {{ include "paths.controllerConfig" . }}: |
    {
      "IdleStop": {{ .Values.idleStop }},
      "LocalDebugMode": false,
      "LogFile": {{ printf "%s/controller.log" (include "paths.logbase" .) | quote }},
      "LogLevel": {{ .Values.logLevel }},
      "JobManagerName": {{ .Values.jobManagerName | quote }},
      "JobManagerWaitPeriod": {{ .Values.startupProbePeriod | default 1 }},
      "KubeConfig": "",
      "KubernetesTimeoutSecs": 60,
      "MinWorkers": {{ .Values.minWorkers }},
      "Period": {{ .Values.autoScalingPeriod }},
      "PreserveSecrets": {{ .Values.preserveSecrets | default false }},
      "ResizePath": {{ printf "%s/resize" (include "paths.binDir" .) | quote }},
      "Network": {
        "BasePort": {{ .Values.basePort }},
        "ClusterDomain": {{ include "derived.clusterDomain" . | quote }},
        "ClusterHost": {{ .Values.clusterHost | quote }},
        "InternalClientsOnly": {{ .Values.internalClientsOnly }},
        "JobManagerPort": {{ include "derived.jobManagerPort" . }},
        "LookupPort": {{ include "derived.lookupPort" . }},
        "MaxWorkers": {{ .Values.maxWorkers }},
        "Namespace": {{ .Release.Namespace | quote}},
        "OpenMetricsPortOutsideKubernetes": {{ .Values.openMetricsPortOutsideKubernetes }},
        "ParallelServerProxyPort": {{ .Values.parallelServerProxyPort }},
        "ParallelServerProxyUseMutualTLS": {{ .Values.parallelServerProxyUseMutualTLS }},
        "PoolProxyBasePort": {{ .Values.poolProxyBasePort }},
        "RequireClientCertificate": {{ .Values.requireClientCertificate }},
        "RequireLdapCert": {{ include "derived.addLDAPCert" . }},
        "RequireScriptVerification": {{ .Values.requireScriptVerification }},
        "SecurityLevel": {{ .Values.securityLevel }},
        "WorkersPerPoolProxy": {{ .Values.workersPerPoolProxy }},
        "UsePoolProxy": {{ include "derived.usePoolProxy" . }},
        "UseParallelServerProxy": {{ include "derived.useParallelServerProxy" . }},
        "UseSecureCommunication": {{ .Values.useSecureCommunication }},
        "UseSecureMetrics": {{ and .Values.exportMetrics .Values.useSecureMetrics }}
      },
      "ResourceNames": {
        "AdminPasswordSecret": {{ include "resources.adminPasswordSecret" . | quote }},
        "AdminPasswordKey": {{ include "resources.adminPasswordKey" . | quote }},
        "CertificateFile": {{ include "paths.certFile" . | quote }},
        "ClientMetricsSecret": {{ include "resources.clientMetricsSecret" . | quote }},
        "ClientMetricsCertFile": {{ include "paths.clientMetricsCert" . | quote }},
        "ClientMetricsKeyFile": {{ include "paths.clientMetricsKey" . | quote }},
        "Controller": {{ include "resources.controller" . | quote }},
        "JobManagerContainer": {{ include "resources.jobManager" . | quote }},
        "JobManagerLabel": {{ printf "app=%s" (include "resources.jobManager" .) | quote }},
        "JobManagerService": {{ include "resources.jobManager" . | quote }},
        "LdapSecret": {{ include "resources.ldapSecret" . | quote }},
        "LdapCertFile": {{ include "paths.ldapCert" . | quote }},
        "LoadBalancer": {{ include "resources.ingressProxy" . | quote }},
        "MetricsSecret": {{ include "resources.metricsSecret" . | quote }},
        "MetricsCaCertFile": {{ include "paths.metricsCaCert" . | quote }},
        "MetricsCertFile": {{ include "paths.metricsCert" . | quote }},
        "MetricsKeyFile": {{ include "paths.metricsKey" . | quote }},
        "ParallelServerProxySecret": {{ include "resources.parallelServerProxySecret" . | quote }},
        "PoolProxyLabel": {{ printf "app=%s" (include "resources.poolProxy" .) | quote }},
        "PoolProxyTemplate": {{ include "resources.poolProxyTemplate" . | quote }},
        "ProfileKey": {{ include "resources.profileKey" . | quote }},
        "ProfileSecret": {{ include "resources.profileSecret" . | quote }},
        "ProfileSecretPre26a": {{ include "resources.profileSecretPre26a" . | quote }},
        "SharedSecret": {{ include "resources.sharedSecret" . | quote }},
        "SharedSecretDir": {{ include "paths.secretDir" . | quote }},
        "SharedSecretFile": {{ include "paths.secretFile" . | quote }},
        "TemplateFile": {{ include "resources.templateFile" . | quote }},
        "WorkerLabel": {{ printf "app=%s" (include "resources.worker" .) | quote }},
        "WorkerTemplate": {{ include "resources.workerTemplate" . | quote }}
      },
      "AnnotationKeys": {
        "CertVolume": {{ include "annotations.certVolume" . | quote }},
        "LogDir": {{ include "annotations.logDir" . | quote }},
        "PoolProxyBasePort": {{ include "annotations.poolProxyBasePort" . | quote }},
        "PoolProxyID": {{ include "annotations.poolProxyID" . | quote }},
        "PoolProxyPrefix": {{ include "annotations.poolProxyPrefix" . | quote }},
        "SecretName": {{ include "annotations.secretName" . | quote }},
        "TemplateChecksum": {{ include "annotations.templateChecksum" . | quote }},
        "UsePoolProxy": {{ include "annotations.usePoolProxy" . | quote }},
        "UseSecureCommunication": {{ include "annotations.useSecureCommunication" . | quote }},
        "WorkerDomain": {{ include "annotations.workerDomain" . | quote }},
        "WorkerID": {{ include "annotations.workerID" . | quote }},
        "WorkerName": {{ include "annotations.workerName" . | quote }},
        "WorkerPrefix": {{ include "annotations.workerPrefix" . | quote }},
        "WorkersPerPoolProxy": {{ include "annotations.workersPerPoolProxy" . | quote }}
      }
    }
