# Bind the MJS controller role to the service account.
# Copyright 2024 The MathWorks, Inc.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "%s-rolebinding" (include "resources.controller" .) }}
subjects:
- kind: ServiceAccount
  name: {{ include "resources.controllerServiceAccount" . }}
roleRef:
  kind: Role
  name: {{ include "resources.controllerRole" . }}
  apiGroup: rbac.authorization.k8s.io