{{- if (eq (include "derived.useParallelServerProxy" . ) "true" ) }}
# Deployment running the parallel server proxy, which proxies all traffic into the cluster.
# Copyright 2025 The MathWorks, Inc.
{{- $name := include "resources.ingressProxy" . }}
{{- if (eq (include "derived.useHAProxy" . ) "true" ) }}
  {{/* If we also need to launch the HAproxy for backwards compatibility, give this deployment a different name */}}
  {{- $name = include "resources.parallelServerProxy" . }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  selector:
    matchLabels:
      app: {{ $name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      # If set to false, disable creation of environment variables for services
      enableServiceLinks: {{ include "derived.enableServiceLinks" . }}

      # Schedule on same nodes as the job manager
      nodeSelector: {{ toJson .Values.jobManagerNodeSelector }}
      tolerations: {{ toJson .Values.jobManagerTolerations }}

      containers:
        - name: {{ include "resources.parallelServerProxy" . }}
          image: {{ .Values.parallelServerProxyImage }}
          imagePullPolicy: {{ .Values.parallelServerProxyImagePullPolicy }}

          # Set optional resource requests and limits
          resources:
            requests:
              {{- if .Values.parallelServerProxyCPURequest }}
              cpu: {{ .Values.parallelServerProxyCPURequest }}
              {{- end }}
              {{- if .Values.parallelServerProxyMemoryRequest }}
              memory: {{ .Values.parallelServerProxyMemoryRequest }}
              {{- end }}
            limits:
              {{- if .Values.parallelServerProxyCPULimit }}
              cpu: {{ .Values.parallelServerProxyCPULimit }}
              {{- end }}
              {{- if .Values.parallelServerProxyMemoryLimit }}
              memory: {{ .Values.parallelServerProxyMemoryLimit }}
              {{- end }}

          args:
          - "-port"
          - {{ .Values.parallelServerProxyPort | quote }}
          {{- if .Values.parallelServerProxyUseMutualTLS }}
          - "-certificate"
          - {{ printf "%s/%s" (include "paths.proxyCertDir" .) (include "paths.certFile" .) | quote }}
          {{- else  }}
          - "-disableMutualTLS"
          {{- end }}
          {{- if ge (int .Values.logLevel) 4 }}
          - "-verbose"
          {{- end }}

          {{- $proxySecretVolName := "proxy-secret-vol" }}
          {{- if .Values.parallelServerProxyUseMutualTLS }}
          volumeMounts:
          - name: {{ $proxySecretVolName}}
            mountPath: {{ include "paths.proxyCertDir" . }}
          {{- end }}

      {{- if .Values.parallelServerProxyUseMutualTLS }}
      volumes:
      - name: {{ $proxySecretVolName }}
        secret:
          secretName: {{ include "resources.parallelServerProxySecret" . }}
      {{- end }}
{{ end -}}
