# ConfigMap containing scripts for the worker pods.
# Copyright 2024-2026 The MathWorks, Inc.
{{- $localMJSDef := "/tmp/mjs_def.sh" }}
{{- $startFile := "/tmp/worker-started" }}
{{- $stopFile := "/tmp/worker-stopped" }}
{{- $additionalMatlabRoots := list }}
{{- if .Values.additionalMatlabPVCs }}
  {{- range $pvc := .Values.additionalMatlabPVCs }}
    {{- $additionalMatlabRoots = append $additionalMatlabRoots (printf "%s/%s" (include "paths.additionalMatlabDir" .) $pvc) }}
  {{- end }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resources.workerConfigMap" . }}
data:
  mjs_def.sh: |
    BASE_PORT={{ .Values.basePort }}
    CHECKPOINTBASE={{ include "paths.checkpointbase" . }}
    PIDBASE=/tmp/pid
    USE_SECURE_COMMUNICATION={{ .Values.useSecureCommunication }}
    REQUIRE_CLIENT_CERTIFICATE={{ .Values.requireClientCertificate }}
    REQUIRE_SCRIPT_VERIFICATION={{ .Values.requireScriptVerification }}
    SECURITY_LEVEL={{ .Values.securityLevel }}
    SHARED_SECRET_FILE={{ include "paths.secretPath" . }}
    USE_ONLINE_LICENSING={{ .Values.useOnlineLicensing }}
    {{- if .Values.javaPVC }}
    MJS_JAVA={{ include "paths.javaDir" . }}
    {{- end }}
    {{- if .Values.additionalMatlabPVCs }}
    MJS_ADDITIONAL_MATLABROOTS={{ join ":" $additionalMatlabRoots }}
    {{- end }}

  worker.sh: |
    #!/usr/bin/env bash
    # Script to run on worker pods
    set -euo pipefail

{{ include "scripts.setMatlabRoot" . | indent 4 }}

    # Set up the mjs_def file
    cp {{ printf "%s/mjs_def.sh" (include "paths.configDir" .) }} {{ $localMJSDef }}
    LOGBASE={{ include "paths.logbase" . }}/${WORKER_NAME}
    SCRIPTLOGFILE=${LOGBASE}/script-log.log
    echo "LOGBASE=${LOGBASE}" >> {{ $localMJSDef }}
    echo "HOSTNAME=${HOSTNAME}" >> {{ $localMJSDef }}

    # Ensure log directory exists and is writeable by workers
    if [ ! -d "${LOGBASE}" ]; then
      mkdir -p "${LOGBASE}"
    fi
    chmod o+w "${LOGBASE}"

    # Create a user to run MATLAB as
    useradd --create-home {{ .Values.workerUsername }} || echo "User {{ .Values.workerUsername }} already exists"
    echo {{ printf "%s:%s" .Values.workerUsername .Values.workerPassword }} | chpasswd

    # Set ulimit to a reasonable value
    ulimit -n {{ .Values.fileDescriptorUlimit | default 4096 }}

    # Start the MJS service
    ${BIN_DIR}/mjs start -mjsdef {{ $localMJSDef }} -loglevel {{ .Values.logLevel }} -disablereliableconnections 2>&1 | tee -a ${SCRIPTLOGFILE}

    # Start the worker
    WORKER_CMD="${BIN_DIR}/startworker -jobmanager \"{{ .Values.jobManagerName }}\" -jobmanagerhost \"{{ include "resources.jobManager" . }}\" -name \"${WORKER_NAME}\" -baseport {{ .Values.basePort | int }} -scriptlogfile ${SCRIPTLOGFILE}"
    {{- if .Values.requireScriptVerification }}
    WORKER_CMD="${WORKER_CMD} -secretfile \"{{ include "paths.secretPath" . }}\""
    {{- end }}
    echo "$(date) | Running startworker command: ${WORKER_CMD}" | tee -a ${SCRIPTLOGFILE}
    eval ${WORKER_CMD} 2>&1 | tee -a ${SCRIPTLOGFILE}

    # Add a file to indicate that startworker is complete
    touch {{ $startFile }}

    # Keep the container running until the worker stops
    echo "$(date) | Started worker. Will keep container running until stop file appears." | tee -a ${SCRIPTLOGFILE}
    while [ ! -f {{ $stopFile | quote }} ]; do
      sleep 1
    done
    echo "$(date) | Found stop file, terminating container." | tee -a ${SCRIPTLOGFILE}

  stopWorker.sh: |
    #!/usr/bin/env bash
    # Script to gracefully shut down a worker
    set -euo pipefail

    # First, wait for startworker to have finished successfully
    SCRIPTLOGFILE=${LOGBASE}/script-log.log
    echo "$(date) | Waiting for startworker to have finished before cleanly stopping worker." | tee -a ${SCRIPTLOGFILE}
    while [ ! -f {{ $startFile | quote }} ]; do
      sleep 1
    done

    # Read the MATLAB root directory determined by the startup script
    MATLAB_ROOT=$(cat {{ include "paths.matlabRootFile" . }})
    BIN_DIR="${MATLAB_ROOT}/toolbox/parallel/bin"

    # Stop the worker
    STOP_CMD="${BIN_DIR}/stopworker -clean -name \"${WORKER_NAME}\" -baseport {{ .Values.basePort | int }} -scriptlogfile ${SCRIPTLOGFILE}"
    {{- if .Values.requireScriptVerification }}
    STOP_CMD="${STOP_CMD} -secretfile \"{{ include "paths.secretPath" . }}\""
    {{- end }}
    eval ${STOP_CMD} 2>&1 | tee -a ${SCRIPTLOGFILE}

    # Trigger the container to exit
    echo "$(date) | Stopped worker. Touching stop file so main container process can exit." | tee -a ${SCRIPTLOGFILE}
    touch {{ $stopFile }}
