// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package setup

import (
	"github.com/mathworks/mjssetup/pkg/profile"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMarshaller creates a new instance of MockMarshaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMarshaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMarshaller {
	mock := &MockMarshaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMarshaller is an autogenerated mock type for the Marshaller type
type MockMarshaller struct {
	mock.Mock
}

type MockMarshaller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMarshaller) EXPECT() *MockMarshaller_Expecter {
	return &MockMarshaller_Expecter{mock: &_m.Mock}
}

// Marshal provides a mock function for the type MockMarshaller
func (_mock *MockMarshaller) Marshal(v any) ([]byte, error) {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Marshal")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(any) ([]byte, error)); ok {
		return returnFunc(v)
	}
	if returnFunc, ok := ret.Get(0).(func(any) []byte); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(any) error); ok {
		r1 = returnFunc(v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarshaller_Marshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Marshal'
type MockMarshaller_Marshal_Call struct {
	*mock.Call
}

// Marshal is a helper method to define mock.On call
//   - v any
func (_e *MockMarshaller_Expecter) Marshal(v interface{}) *MockMarshaller_Marshal_Call {
	return &MockMarshaller_Marshal_Call{Call: _e.mock.On("Marshal", v)}
}

func (_c *MockMarshaller_Marshal_Call) Run(run func(v any)) *MockMarshaller_Marshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMarshaller_Marshal_Call) Return(bytes []byte, err error) *MockMarshaller_Marshal_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockMarshaller_Marshal_Call) RunAndReturn(run func(v any) ([]byte, error)) *MockMarshaller_Marshal_Call {
	_c.Call.Return(run)
	return _c
}

// UnmarshalProfile provides a mock function for the type MockMarshaller
func (_mock *MockMarshaller) UnmarshalProfile(bytes []byte) (*profile.Profile, error) {
	ret := _mock.Called(bytes)

	if len(ret) == 0 {
		panic("no return value specified for UnmarshalProfile")
	}

	var r0 *profile.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (*profile.Profile, error)); ok {
		return returnFunc(bytes)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) *profile.Profile); ok {
		r0 = returnFunc(bytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profile.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMarshaller_UnmarshalProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnmarshalProfile'
type MockMarshaller_UnmarshalProfile_Call struct {
	*mock.Call
}

// UnmarshalProfile is a helper method to define mock.On call
//   - bytes []byte
func (_e *MockMarshaller_Expecter) UnmarshalProfile(bytes interface{}) *MockMarshaller_UnmarshalProfile_Call {
	return &MockMarshaller_UnmarshalProfile_Call{Call: _e.mock.On("UnmarshalProfile", bytes)}
}

func (_c *MockMarshaller_UnmarshalProfile_Call) Run(run func(bytes []byte)) *MockMarshaller_UnmarshalProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMarshaller_UnmarshalProfile_Call) Return(profile1 *profile.Profile, err error) *MockMarshaller_UnmarshalProfile_Call {
	_c.Call.Return(profile1, err)
	return _c
}

func (_c *MockMarshaller_UnmarshalProfile_Call) RunAndReturn(run func(bytes []byte) (*profile.Profile, error)) *MockMarshaller_UnmarshalProfile_Call {
	_c.Call.Return(run)
	return _c
}
