// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package setup

import (
	"controller/internal/certificate"

	"github.com/mathworks/mjssetup/pkg/profile"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProfileCreator creates a new instance of MockProfileCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileCreator {
	mock := &MockProfileCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileCreator is an autogenerated mock type for the ProfileCreator type
type MockProfileCreator struct {
	mock.Mock
}

type MockProfileCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileCreator) EXPECT() *MockProfileCreator_Expecter {
	return &MockProfileCreator_Expecter{mock: &_m.Mock}
}

// CreateProfile provides a mock function for the type MockProfileCreator
func (_mock *MockProfileCreator) CreateProfile(hostname string, cert *certificate.Certificate, forSocks bool) *profile.Profile {
	ret := _mock.Called(hostname, cert, forSocks)

	if len(ret) == 0 {
		panic("no return value specified for CreateProfile")
	}

	var r0 *profile.Profile
	if returnFunc, ok := ret.Get(0).(func(string, *certificate.Certificate, bool) *profile.Profile); ok {
		r0 = returnFunc(hostname, cert, forSocks)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profile.Profile)
		}
	}
	return r0
}

// MockProfileCreator_CreateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProfile'
type MockProfileCreator_CreateProfile_Call struct {
	*mock.Call
}

// CreateProfile is a helper method to define mock.On call
//   - hostname string
//   - cert *certificate.Certificate
//   - forSocks bool
func (_e *MockProfileCreator_Expecter) CreateProfile(hostname interface{}, cert interface{}, forSocks interface{}) *MockProfileCreator_CreateProfile_Call {
	return &MockProfileCreator_CreateProfile_Call{Call: _e.mock.On("CreateProfile", hostname, cert, forSocks)}
}

func (_c *MockProfileCreator_CreateProfile_Call) Run(run func(hostname string, cert *certificate.Certificate, forSocks bool)) *MockProfileCreator_CreateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *certificate.Certificate
		if args[1] != nil {
			arg1 = args[1].(*certificate.Certificate)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProfileCreator_CreateProfile_Call) Return(profile1 *profile.Profile) *MockProfileCreator_CreateProfile_Call {
	_c.Call.Return(profile1)
	return _c
}

func (_c *MockProfileCreator_CreateProfile_Call) RunAndReturn(run func(hostname string, cert *certificate.Certificate, forSocks bool) *profile.Profile) *MockProfileCreator_CreateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// IsConsistent provides a mock function for the type MockProfileCreator
func (_mock *MockProfileCreator) IsConsistent(profile1 *profile.Profile, hostname string, secret *certificate.SharedSecret, needCert bool, forSocks bool) bool {
	ret := _mock.Called(profile1, hostname, secret, needCert, forSocks)

	if len(ret) == 0 {
		panic("no return value specified for IsConsistent")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(*profile.Profile, string, *certificate.SharedSecret, bool, bool) bool); ok {
		r0 = returnFunc(profile1, hostname, secret, needCert, forSocks)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockProfileCreator_IsConsistent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConsistent'
type MockProfileCreator_IsConsistent_Call struct {
	*mock.Call
}

// IsConsistent is a helper method to define mock.On call
//   - profile1 *profile.Profile
//   - hostname string
//   - secret *certificate.SharedSecret
//   - needCert bool
//   - forSocks bool
func (_e *MockProfileCreator_Expecter) IsConsistent(profile1 interface{}, hostname interface{}, secret interface{}, needCert interface{}, forSocks interface{}) *MockProfileCreator_IsConsistent_Call {
	return &MockProfileCreator_IsConsistent_Call{Call: _e.mock.On("IsConsistent", profile1, hostname, secret, needCert, forSocks)}
}

func (_c *MockProfileCreator_IsConsistent_Call) Run(run func(profile1 *profile.Profile, hostname string, secret *certificate.SharedSecret, needCert bool, forSocks bool)) *MockProfileCreator_IsConsistent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *profile.Profile
		if args[0] != nil {
			arg0 = args[0].(*profile.Profile)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *certificate.SharedSecret
		if args[2] != nil {
			arg2 = args[2].(*certificate.SharedSecret)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockProfileCreator_IsConsistent_Call) Return(b bool) *MockProfileCreator_IsConsistent_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockProfileCreator_IsConsistent_Call) RunAndReturn(run func(profile1 *profile.Profile, hostname string, secret *certificate.SharedSecret, needCert bool, forSocks bool) bool) *MockProfileCreator_IsConsistent_Call {
	_c.Call.Return(run)
	return _c
}
