// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package k8s

import (
	"bytes"

	mock "github.com/stretchr/testify/mock"
	"k8s.io/api/apps/v1"
	v10 "k8s.io/api/core/v1"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CreateDeployment provides a mock function for the type MockClient
func (_mock *MockClient) CreateDeployment(deployment *v1.Deployment) (*v1.Deployment, error) {
	ret := _mock.Called(deployment)

	if len(ret) == 0 {
		panic("no return value specified for CreateDeployment")
	}

	var r0 *v1.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*v1.Deployment) (*v1.Deployment, error)); ok {
		return returnFunc(deployment)
	}
	if returnFunc, ok := ret.Get(0).(func(*v1.Deployment) *v1.Deployment); ok {
		r0 = returnFunc(deployment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*v1.Deployment) error); ok {
		r1 = returnFunc(deployment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDeployment'
type MockClient_CreateDeployment_Call struct {
	*mock.Call
}

// CreateDeployment is a helper method to define mock.On call
//   - deployment *v1.Deployment
func (_e *MockClient_Expecter) CreateDeployment(deployment interface{}) *MockClient_CreateDeployment_Call {
	return &MockClient_CreateDeployment_Call{Call: _e.mock.On("CreateDeployment", deployment)}
}

func (_c *MockClient_CreateDeployment_Call) Run(run func(deployment *v1.Deployment)) *MockClient_CreateDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *v1.Deployment
		if args[0] != nil {
			arg0 = args[0].(*v1.Deployment)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_CreateDeployment_Call) Return(deployment1 *v1.Deployment, err error) *MockClient_CreateDeployment_Call {
	_c.Call.Return(deployment1, err)
	return _c
}

func (_c *MockClient_CreateDeployment_Call) RunAndReturn(run func(deployment *v1.Deployment) (*v1.Deployment, error)) *MockClient_CreateDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePod provides a mock function for the type MockClient
func (_mock *MockClient) CreatePod(pod *v10.Pod) (*v10.Pod, error) {
	ret := _mock.Called(pod)

	if len(ret) == 0 {
		panic("no return value specified for CreatePod")
	}

	var r0 *v10.Pod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*v10.Pod) (*v10.Pod, error)); ok {
		return returnFunc(pod)
	}
	if returnFunc, ok := ret.Get(0).(func(*v10.Pod) *v10.Pod); ok {
		r0 = returnFunc(pod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.Pod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*v10.Pod) error); ok {
		r1 = returnFunc(pod)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreatePod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePod'
type MockClient_CreatePod_Call struct {
	*mock.Call
}

// CreatePod is a helper method to define mock.On call
//   - pod *v10.Pod
func (_e *MockClient_Expecter) CreatePod(pod interface{}) *MockClient_CreatePod_Call {
	return &MockClient_CreatePod_Call{Call: _e.mock.On("CreatePod", pod)}
}

func (_c *MockClient_CreatePod_Call) Run(run func(pod *v10.Pod)) *MockClient_CreatePod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *v10.Pod
		if args[0] != nil {
			arg0 = args[0].(*v10.Pod)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_CreatePod_Call) Return(pod1 *v10.Pod, err error) *MockClient_CreatePod_Call {
	_c.Call.Return(pod1, err)
	return _c
}

func (_c *MockClient_CreatePod_Call) RunAndReturn(run func(pod *v10.Pod) (*v10.Pod, error)) *MockClient_CreatePod_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSecret provides a mock function for the type MockClient
func (_mock *MockClient) CreateSecret(s string, stringToBytes map[string][]byte, b bool) (*v10.Secret, error) {
	ret := _mock.Called(s, stringToBytes, b)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 *v10.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, map[string][]byte, bool) (*v10.Secret, error)); ok {
		return returnFunc(s, stringToBytes, b)
	}
	if returnFunc, ok := ret.Get(0).(func(string, map[string][]byte, bool) *v10.Secret); ok {
		r0 = returnFunc(s, stringToBytes, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, map[string][]byte, bool) error); ok {
		r1 = returnFunc(s, stringToBytes, b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecret'
type MockClient_CreateSecret_Call struct {
	*mock.Call
}

// CreateSecret is a helper method to define mock.On call
//   - s string
//   - stringToBytes map[string][]byte
//   - b bool
func (_e *MockClient_Expecter) CreateSecret(s interface{}, stringToBytes interface{}, b interface{}) *MockClient_CreateSecret_Call {
	return &MockClient_CreateSecret_Call{Call: _e.mock.On("CreateSecret", s, stringToBytes, b)}
}

func (_c *MockClient_CreateSecret_Call) Run(run func(s string, stringToBytes map[string][]byte, b bool)) *MockClient_CreateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 map[string][]byte
		if args[1] != nil {
			arg1 = args[1].(map[string][]byte)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_CreateSecret_Call) Return(secret *v10.Secret, err error) *MockClient_CreateSecret_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockClient_CreateSecret_Call) RunAndReturn(run func(s string, stringToBytes map[string][]byte, b bool) (*v10.Secret, error)) *MockClient_CreateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDeployment provides a mock function for the type MockClient
func (_mock *MockClient) DeleteDeployment(s string) error {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDeployment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDeployment'
type MockClient_DeleteDeployment_Call struct {
	*mock.Call
}

// DeleteDeployment is a helper method to define mock.On call
//   - s string
func (_e *MockClient_Expecter) DeleteDeployment(s interface{}) *MockClient_DeleteDeployment_Call {
	return &MockClient_DeleteDeployment_Call{Call: _e.mock.On("DeleteDeployment", s)}
}

func (_c *MockClient_DeleteDeployment_Call) Run(run func(s string)) *MockClient_DeleteDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_DeleteDeployment_Call) Return(err error) *MockClient_DeleteDeployment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteDeployment_Call) RunAndReturn(run func(s string) error) *MockClient_DeleteDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePod provides a mock function for the type MockClient
func (_mock *MockClient) DeletePod(s string) error {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for DeletePod")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeletePod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePod'
type MockClient_DeletePod_Call struct {
	*mock.Call
}

// DeletePod is a helper method to define mock.On call
//   - s string
func (_e *MockClient_Expecter) DeletePod(s interface{}) *MockClient_DeletePod_Call {
	return &MockClient_DeletePod_Call{Call: _e.mock.On("DeletePod", s)}
}

func (_c *MockClient_DeletePod_Call) Run(run func(s string)) *MockClient_DeletePod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_DeletePod_Call) Return(err error) *MockClient_DeletePod_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeletePod_Call) RunAndReturn(run func(s string) error) *MockClient_DeletePod_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecret provides a mock function for the type MockClient
func (_mock *MockClient) DeleteSecret(s string) error {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type MockClient_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - s string
func (_e *MockClient_Expecter) DeleteSecret(s interface{}) *MockClient_DeleteSecret_Call {
	return &MockClient_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret", s)}
}

func (_c *MockClient_DeleteSecret_Call) Run(run func(s string)) *MockClient_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_DeleteSecret_Call) Return(err error) *MockClient_DeleteSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteSecret_Call) RunAndReturn(run func(s string) error) *MockClient_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DeploymentExists provides a mock function for the type MockClient
func (_mock *MockClient) DeploymentExists(s string) (bool, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for DeploymentExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_DeploymentExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeploymentExists'
type MockClient_DeploymentExists_Call struct {
	*mock.Call
}

// DeploymentExists is a helper method to define mock.On call
//   - s string
func (_e *MockClient_Expecter) DeploymentExists(s interface{}) *MockClient_DeploymentExists_Call {
	return &MockClient_DeploymentExists_Call{Call: _e.mock.On("DeploymentExists", s)}
}

func (_c *MockClient_DeploymentExists_Call) Run(run func(s string)) *MockClient_DeploymentExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_DeploymentExists_Call) Return(b bool, err error) *MockClient_DeploymentExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockClient_DeploymentExists_Call) RunAndReturn(run func(s string) (bool, error)) *MockClient_DeploymentExists_Call {
	_c.Call.Return(run)
	return _c
}

// ExecOnPod provides a mock function for the type MockClient
func (_mock *MockClient) ExecOnPod(podName string, containerName string, cmd []string) (*bytes.Buffer, error) {
	ret := _mock.Called(podName, containerName, cmd)

	if len(ret) == 0 {
		panic("no return value specified for ExecOnPod")
	}

	var r0 *bytes.Buffer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, []string) (*bytes.Buffer, error)); ok {
		return returnFunc(podName, containerName, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, []string) *bytes.Buffer); ok {
		r0 = returnFunc(podName, containerName, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bytes.Buffer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, []string) error); ok {
		r1 = returnFunc(podName, containerName, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ExecOnPod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecOnPod'
type MockClient_ExecOnPod_Call struct {
	*mock.Call
}

// ExecOnPod is a helper method to define mock.On call
//   - podName string
//   - containerName string
//   - cmd []string
func (_e *MockClient_Expecter) ExecOnPod(podName interface{}, containerName interface{}, cmd interface{}) *MockClient_ExecOnPod_Call {
	return &MockClient_ExecOnPod_Call{Call: _e.mock.On("ExecOnPod", podName, containerName, cmd)}
}

func (_c *MockClient_ExecOnPod_Call) Run(run func(podName string, containerName string, cmd []string)) *MockClient_ExecOnPod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ExecOnPod_Call) Return(buffer *bytes.Buffer, err error) *MockClient_ExecOnPod_Call {
	_c.Call.Return(buffer, err)
	return _c
}

func (_c *MockClient_ExecOnPod_Call) RunAndReturn(run func(podName string, containerName string, cmd []string) (*bytes.Buffer, error)) *MockClient_ExecOnPod_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfigMap provides a mock function for the type MockClient
func (_mock *MockClient) GetConfigMap(s string) (*v10.ConfigMap, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetConfigMap")
	}

	var r0 *v10.ConfigMap
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*v10.ConfigMap, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *v10.ConfigMap); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.ConfigMap)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetConfigMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigMap'
type MockClient_GetConfigMap_Call struct {
	*mock.Call
}

// GetConfigMap is a helper method to define mock.On call
//   - s string
func (_e *MockClient_Expecter) GetConfigMap(s interface{}) *MockClient_GetConfigMap_Call {
	return &MockClient_GetConfigMap_Call{Call: _e.mock.On("GetConfigMap", s)}
}

func (_c *MockClient_GetConfigMap_Call) Run(run func(s string)) *MockClient_GetConfigMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetConfigMap_Call) Return(configMap *v10.ConfigMap, err error) *MockClient_GetConfigMap_Call {
	_c.Call.Return(configMap, err)
	return _c
}

func (_c *MockClient_GetConfigMap_Call) RunAndReturn(run func(s string) (*v10.ConfigMap, error)) *MockClient_GetConfigMap_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeployment provides a mock function for the type MockClient
func (_mock *MockClient) GetDeployment(s string) (*v1.Deployment, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetDeployment")
	}

	var r0 *v1.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*v1.Deployment, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *v1.Deployment); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeployment'
type MockClient_GetDeployment_Call struct {
	*mock.Call
}

// GetDeployment is a helper method to define mock.On call
//   - s string
func (_e *MockClient_Expecter) GetDeployment(s interface{}) *MockClient_GetDeployment_Call {
	return &MockClient_GetDeployment_Call{Call: _e.mock.On("GetDeployment", s)}
}

func (_c *MockClient_GetDeployment_Call) Run(run func(s string)) *MockClient_GetDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetDeployment_Call) Return(deployment *v1.Deployment, err error) *MockClient_GetDeployment_Call {
	_c.Call.Return(deployment, err)
	return _c
}

func (_c *MockClient_GetDeployment_Call) RunAndReturn(run func(s string) (*v1.Deployment, error)) *MockClient_GetDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeploymentsWithLabel provides a mock function for the type MockClient
func (_mock *MockClient) GetDeploymentsWithLabel(s string) (*v1.DeploymentList, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetDeploymentsWithLabel")
	}

	var r0 *v1.DeploymentList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*v1.DeploymentList, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *v1.DeploymentList); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.DeploymentList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetDeploymentsWithLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeploymentsWithLabel'
type MockClient_GetDeploymentsWithLabel_Call struct {
	*mock.Call
}

// GetDeploymentsWithLabel is a helper method to define mock.On call
//   - s string
func (_e *MockClient_Expecter) GetDeploymentsWithLabel(s interface{}) *MockClient_GetDeploymentsWithLabel_Call {
	return &MockClient_GetDeploymentsWithLabel_Call{Call: _e.mock.On("GetDeploymentsWithLabel", s)}
}

func (_c *MockClient_GetDeploymentsWithLabel_Call) Run(run func(s string)) *MockClient_GetDeploymentsWithLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetDeploymentsWithLabel_Call) Return(deploymentList *v1.DeploymentList, err error) *MockClient_GetDeploymentsWithLabel_Call {
	_c.Call.Return(deploymentList, err)
	return _c
}

func (_c *MockClient_GetDeploymentsWithLabel_Call) RunAndReturn(run func(s string) (*v1.DeploymentList, error)) *MockClient_GetDeploymentsWithLabel_Call {
	_c.Call.Return(run)
	return _c
}

// GetPod provides a mock function for the type MockClient
func (_mock *MockClient) GetPod(s string) (*v10.Pod, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetPod")
	}

	var r0 *v10.Pod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*v10.Pod, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *v10.Pod); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.Pod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetPod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPod'
type MockClient_GetPod_Call struct {
	*mock.Call
}

// GetPod is a helper method to define mock.On call
//   - s string
func (_e *MockClient_Expecter) GetPod(s interface{}) *MockClient_GetPod_Call {
	return &MockClient_GetPod_Call{Call: _e.mock.On("GetPod", s)}
}

func (_c *MockClient_GetPod_Call) Run(run func(s string)) *MockClient_GetPod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetPod_Call) Return(pod *v10.Pod, err error) *MockClient_GetPod_Call {
	_c.Call.Return(pod, err)
	return _c
}

func (_c *MockClient_GetPod_Call) RunAndReturn(run func(s string) (*v10.Pod, error)) *MockClient_GetPod_Call {
	_c.Call.Return(run)
	return _c
}

// GetPodsWithLabel provides a mock function for the type MockClient
func (_mock *MockClient) GetPodsWithLabel(s string) (*v10.PodList, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetPodsWithLabel")
	}

	var r0 *v10.PodList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*v10.PodList, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *v10.PodList); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.PodList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetPodsWithLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPodsWithLabel'
type MockClient_GetPodsWithLabel_Call struct {
	*mock.Call
}

// GetPodsWithLabel is a helper method to define mock.On call
//   - s string
func (_e *MockClient_Expecter) GetPodsWithLabel(s interface{}) *MockClient_GetPodsWithLabel_Call {
	return &MockClient_GetPodsWithLabel_Call{Call: _e.mock.On("GetPodsWithLabel", s)}
}

func (_c *MockClient_GetPodsWithLabel_Call) Run(run func(s string)) *MockClient_GetPodsWithLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetPodsWithLabel_Call) Return(podList *v10.PodList, err error) *MockClient_GetPodsWithLabel_Call {
	_c.Call.Return(podList, err)
	return _c
}

func (_c *MockClient_GetPodsWithLabel_Call) RunAndReturn(run func(s string) (*v10.PodList, error)) *MockClient_GetPodsWithLabel_Call {
	_c.Call.Return(run)
	return _c
}

// GetReadyPod provides a mock function for the type MockClient
func (_mock *MockClient) GetReadyPod(label string, containerName string) (*v10.Pod, error) {
	ret := _mock.Called(label, containerName)

	if len(ret) == 0 {
		panic("no return value specified for GetReadyPod")
	}

	var r0 *v10.Pod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*v10.Pod, error)); ok {
		return returnFunc(label, containerName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *v10.Pod); ok {
		r0 = returnFunc(label, containerName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.Pod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(label, containerName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetReadyPod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReadyPod'
type MockClient_GetReadyPod_Call struct {
	*mock.Call
}

// GetReadyPod is a helper method to define mock.On call
//   - label string
//   - containerName string
func (_e *MockClient_Expecter) GetReadyPod(label interface{}, containerName interface{}) *MockClient_GetReadyPod_Call {
	return &MockClient_GetReadyPod_Call{Call: _e.mock.On("GetReadyPod", label, containerName)}
}

func (_c *MockClient_GetReadyPod_Call) Run(run func(label string, containerName string)) *MockClient_GetReadyPod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetReadyPod_Call) Return(pod *v10.Pod, err error) *MockClient_GetReadyPod_Call {
	_c.Call.Return(pod, err)
	return _c
}

func (_c *MockClient_GetReadyPod_Call) RunAndReturn(run func(label string, containerName string) (*v10.Pod, error)) *MockClient_GetReadyPod_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function for the type MockClient
func (_mock *MockClient) GetSecret(s string) (*v10.Secret, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 *v10.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*v10.Secret, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *v10.Secret); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockClient_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - s string
func (_e *MockClient_Expecter) GetSecret(s interface{}) *MockClient_GetSecret_Call {
	return &MockClient_GetSecret_Call{Call: _e.mock.On("GetSecret", s)}
}

func (_c *MockClient_GetSecret_Call) Run(run func(s string)) *MockClient_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetSecret_Call) Return(secret *v10.Secret, err error) *MockClient_GetSecret_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockClient_GetSecret_Call) RunAndReturn(run func(s string) (*v10.Secret, error)) *MockClient_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetService provides a mock function for the type MockClient
func (_mock *MockClient) GetService(s string) (*v10.Service, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetService")
	}

	var r0 *v10.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*v10.Service, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *v10.Service); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetService'
type MockClient_GetService_Call struct {
	*mock.Call
}

// GetService is a helper method to define mock.On call
//   - s string
func (_e *MockClient_Expecter) GetService(s interface{}) *MockClient_GetService_Call {
	return &MockClient_GetService_Call{Call: _e.mock.On("GetService", s)}
}

func (_c *MockClient_GetService_Call) Run(run func(s string)) *MockClient_GetService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetService_Call) Return(service *v10.Service, err error) *MockClient_GetService_Call {
	_c.Call.Return(service, err)
	return _c
}

func (_c *MockClient_GetService_Call) RunAndReturn(run func(s string) (*v10.Service, error)) *MockClient_GetService_Call {
	_c.Call.Return(run)
	return _c
}

// GetServicesWithLabel provides a mock function for the type MockClient
func (_mock *MockClient) GetServicesWithLabel(s string) (*v10.ServiceList, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetServicesWithLabel")
	}

	var r0 *v10.ServiceList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*v10.ServiceList, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *v10.ServiceList); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.ServiceList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetServicesWithLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServicesWithLabel'
type MockClient_GetServicesWithLabel_Call struct {
	*mock.Call
}

// GetServicesWithLabel is a helper method to define mock.On call
//   - s string
func (_e *MockClient_Expecter) GetServicesWithLabel(s interface{}) *MockClient_GetServicesWithLabel_Call {
	return &MockClient_GetServicesWithLabel_Call{Call: _e.mock.On("GetServicesWithLabel", s)}
}

func (_c *MockClient_GetServicesWithLabel_Call) Run(run func(s string)) *MockClient_GetServicesWithLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetServicesWithLabel_Call) Return(serviceList *v10.ServiceList, err error) *MockClient_GetServicesWithLabel_Call {
	_c.Call.Return(serviceList, err)
	return _c
}

func (_c *MockClient_GetServicesWithLabel_Call) RunAndReturn(run func(s string) (*v10.ServiceList, error)) *MockClient_GetServicesWithLabel_Call {
	_c.Call.Return(run)
	return _c
}

// IsPodReady provides a mock function for the type MockClient
func (_mock *MockClient) IsPodReady(label string, containerName string) (bool, error) {
	ret := _mock.Called(label, containerName)

	if len(ret) == 0 {
		panic("no return value specified for IsPodReady")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return returnFunc(label, containerName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(label, containerName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(label, containerName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_IsPodReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsPodReady'
type MockClient_IsPodReady_Call struct {
	*mock.Call
}

// IsPodReady is a helper method to define mock.On call
//   - label string
//   - containerName string
func (_e *MockClient_Expecter) IsPodReady(label interface{}, containerName interface{}) *MockClient_IsPodReady_Call {
	return &MockClient_IsPodReady_Call{Call: _e.mock.On("IsPodReady", label, containerName)}
}

func (_c *MockClient_IsPodReady_Call) Run(run func(label string, containerName string)) *MockClient_IsPodReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_IsPodReady_Call) Return(b bool, err error) *MockClient_IsPodReady_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockClient_IsPodReady_Call) RunAndReturn(run func(label string, containerName string) (bool, error)) *MockClient_IsPodReady_Call {
	_c.Call.Return(run)
	return _c
}

// SecretExists provides a mock function for the type MockClient
func (_mock *MockClient) SecretExists(s string) (*v10.Secret, bool, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for SecretExists")
	}

	var r0 *v10.Secret
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (*v10.Secret, bool, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *v10.Secret); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(s)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockClient_SecretExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SecretExists'
type MockClient_SecretExists_Call struct {
	*mock.Call
}

// SecretExists is a helper method to define mock.On call
//   - s string
func (_e *MockClient_Expecter) SecretExists(s interface{}) *MockClient_SecretExists_Call {
	return &MockClient_SecretExists_Call{Call: _e.mock.On("SecretExists", s)}
}

func (_c *MockClient_SecretExists_Call) Run(run func(s string)) *MockClient_SecretExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_SecretExists_Call) Return(secret *v10.Secret, b bool, err error) *MockClient_SecretExists_Call {
	_c.Call.Return(secret, b, err)
	return _c
}

func (_c *MockClient_SecretExists_Call) RunAndReturn(run func(s string) (*v10.Secret, bool, error)) *MockClient_SecretExists_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceExists provides a mock function for the type MockClient
func (_mock *MockClient) ServiceExists(s string) (*v10.Service, bool, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for ServiceExists")
	}

	var r0 *v10.Service
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (*v10.Service, bool, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *v10.Service); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(s)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockClient_ServiceExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceExists'
type MockClient_ServiceExists_Call struct {
	*mock.Call
}

// ServiceExists is a helper method to define mock.On call
//   - s string
func (_e *MockClient_Expecter) ServiceExists(s interface{}) *MockClient_ServiceExists_Call {
	return &MockClient_ServiceExists_Call{Call: _e.mock.On("ServiceExists", s)}
}

func (_c *MockClient_ServiceExists_Call) Run(run func(s string)) *MockClient_ServiceExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_ServiceExists_Call) Return(service *v10.Service, b bool, err error) *MockClient_ServiceExists_Call {
	_c.Call.Return(service, b, err)
	return _c
}

func (_c *MockClient_ServiceExists_Call) RunAndReturn(run func(s string) (*v10.Service, bool, error)) *MockClient_ServiceExists_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDeployment provides a mock function for the type MockClient
func (_mock *MockClient) UpdateDeployment(deployment *v1.Deployment) (*v1.Deployment, error) {
	ret := _mock.Called(deployment)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDeployment")
	}

	var r0 *v1.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*v1.Deployment) (*v1.Deployment, error)); ok {
		return returnFunc(deployment)
	}
	if returnFunc, ok := ret.Get(0).(func(*v1.Deployment) *v1.Deployment); ok {
		r0 = returnFunc(deployment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*v1.Deployment) error); ok {
		r1 = returnFunc(deployment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_UpdateDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDeployment'
type MockClient_UpdateDeployment_Call struct {
	*mock.Call
}

// UpdateDeployment is a helper method to define mock.On call
//   - deployment *v1.Deployment
func (_e *MockClient_Expecter) UpdateDeployment(deployment interface{}) *MockClient_UpdateDeployment_Call {
	return &MockClient_UpdateDeployment_Call{Call: _e.mock.On("UpdateDeployment", deployment)}
}

func (_c *MockClient_UpdateDeployment_Call) Run(run func(deployment *v1.Deployment)) *MockClient_UpdateDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *v1.Deployment
		if args[0] != nil {
			arg0 = args[0].(*v1.Deployment)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_UpdateDeployment_Call) Return(deployment1 *v1.Deployment, err error) *MockClient_UpdateDeployment_Call {
	_c.Call.Return(deployment1, err)
	return _c
}

func (_c *MockClient_UpdateDeployment_Call) RunAndReturn(run func(deployment *v1.Deployment) (*v1.Deployment, error)) *MockClient_UpdateDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecret provides a mock function for the type MockClient
func (_mock *MockClient) UpdateSecret(s string, stringToBytes map[string][]byte, b bool) (*v10.Secret, error) {
	ret := _mock.Called(s, stringToBytes, b)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecret")
	}

	var r0 *v10.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, map[string][]byte, bool) (*v10.Secret, error)); ok {
		return returnFunc(s, stringToBytes, b)
	}
	if returnFunc, ok := ret.Get(0).(func(string, map[string][]byte, bool) *v10.Secret); ok {
		r0 = returnFunc(s, stringToBytes, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, map[string][]byte, bool) error); ok {
		r1 = returnFunc(s, stringToBytes, b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_UpdateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecret'
type MockClient_UpdateSecret_Call struct {
	*mock.Call
}

// UpdateSecret is a helper method to define mock.On call
//   - s string
//   - stringToBytes map[string][]byte
//   - b bool
func (_e *MockClient_Expecter) UpdateSecret(s interface{}, stringToBytes interface{}, b interface{}) *MockClient_UpdateSecret_Call {
	return &MockClient_UpdateSecret_Call{Call: _e.mock.On("UpdateSecret", s, stringToBytes, b)}
}

func (_c *MockClient_UpdateSecret_Call) Run(run func(s string, stringToBytes map[string][]byte, b bool)) *MockClient_UpdateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 map[string][]byte
		if args[1] != nil {
			arg1 = args[1].(map[string][]byte)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_UpdateSecret_Call) Return(secret *v10.Secret, err error) *MockClient_UpdateSecret_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockClient_UpdateSecret_Call) RunAndReturn(run func(s string, stringToBytes map[string][]byte, b bool) (*v10.Secret, error)) *MockClient_UpdateSecret_Call {
	_c.Call.Return(run)
	return _c
}
