// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package specs

import (
	mock "github.com/stretchr/testify/mock"
	"k8s.io/api/core/v1"
)

// NewMockTemplateStore creates a new instance of MockTemplateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplateStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplateStore {
	mock := &MockTemplateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTemplateStore is an autogenerated mock type for the TemplateStore type
type MockTemplateStore struct {
	mock.Mock
}

type MockTemplateStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplateStore) EXPECT() *MockTemplateStore_Expecter {
	return &MockTemplateStore_Expecter{mock: &_m.Mock}
}

// GetPoolProxyPodTemplate provides a mock function for the type MockTemplateStore
func (_mock *MockTemplateStore) GetPoolProxyPodTemplate() (*v1.PodTemplateSpec, string) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPoolProxyPodTemplate")
	}

	var r0 *v1.PodTemplateSpec
	var r1 string
	if returnFunc, ok := ret.Get(0).(func() (*v1.PodTemplateSpec, string)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *v1.PodTemplateSpec); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.PodTemplateSpec)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	return r0, r1
}

// MockTemplateStore_GetPoolProxyPodTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPoolProxyPodTemplate'
type MockTemplateStore_GetPoolProxyPodTemplate_Call struct {
	*mock.Call
}

// GetPoolProxyPodTemplate is a helper method to define mock.On call
func (_e *MockTemplateStore_Expecter) GetPoolProxyPodTemplate() *MockTemplateStore_GetPoolProxyPodTemplate_Call {
	return &MockTemplateStore_GetPoolProxyPodTemplate_Call{Call: _e.mock.On("GetPoolProxyPodTemplate")}
}

func (_c *MockTemplateStore_GetPoolProxyPodTemplate_Call) Run(run func()) *MockTemplateStore_GetPoolProxyPodTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTemplateStore_GetPoolProxyPodTemplate_Call) Return(podTemplateSpec *v1.PodTemplateSpec, s string) *MockTemplateStore_GetPoolProxyPodTemplate_Call {
	_c.Call.Return(podTemplateSpec, s)
	return _c
}

func (_c *MockTemplateStore_GetPoolProxyPodTemplate_Call) RunAndReturn(run func() (*v1.PodTemplateSpec, string)) *MockTemplateStore_GetPoolProxyPodTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkerPodTemplate provides a mock function for the type MockTemplateStore
func (_mock *MockTemplateStore) GetWorkerPodTemplate() (*v1.PodTemplateSpec, string) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetWorkerPodTemplate")
	}

	var r0 *v1.PodTemplateSpec
	var r1 string
	if returnFunc, ok := ret.Get(0).(func() (*v1.PodTemplateSpec, string)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *v1.PodTemplateSpec); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.PodTemplateSpec)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	return r0, r1
}

// MockTemplateStore_GetWorkerPodTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkerPodTemplate'
type MockTemplateStore_GetWorkerPodTemplate_Call struct {
	*mock.Call
}

// GetWorkerPodTemplate is a helper method to define mock.On call
func (_e *MockTemplateStore_Expecter) GetWorkerPodTemplate() *MockTemplateStore_GetWorkerPodTemplate_Call {
	return &MockTemplateStore_GetWorkerPodTemplate_Call{Call: _e.mock.On("GetWorkerPodTemplate")}
}

func (_c *MockTemplateStore_GetWorkerPodTemplate_Call) Run(run func()) *MockTemplateStore_GetWorkerPodTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTemplateStore_GetWorkerPodTemplate_Call) Return(podTemplateSpec *v1.PodTemplateSpec, s string) *MockTemplateStore_GetWorkerPodTemplate_Call {
	_c.Call.Return(podTemplateSpec, s)
	return _c
}

func (_c *MockTemplateStore_GetWorkerPodTemplate_Call) RunAndReturn(run func() (*v1.PodTemplateSpec, string)) *MockTemplateStore_GetWorkerPodTemplate_Call {
	_c.Call.Return(run)
	return _c
}
