// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controller

import (
	"controller/internal/controller"

	mock "github.com/stretchr/testify/mock"
)

// NewMockResizeRequestGetter creates a new instance of MockResizeRequestGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResizeRequestGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResizeRequestGetter {
	mock := &MockResizeRequestGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResizeRequestGetter is an autogenerated mock type for the ResizeRequestGetter type
type MockResizeRequestGetter struct {
	mock.Mock
}

type MockResizeRequestGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResizeRequestGetter) EXPECT() *MockResizeRequestGetter_Expecter {
	return &MockResizeRequestGetter_Expecter{mock: &_m.Mock}
}

// GetRequest provides a mock function for the type MockResizeRequestGetter
func (_mock *MockResizeRequestGetter) GetRequest() (*controller.ResizeRequest, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRequest")
	}

	var r0 *controller.ResizeRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*controller.ResizeRequest, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *controller.ResizeRequest); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*controller.ResizeRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResizeRequestGetter_GetRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequest'
type MockResizeRequestGetter_GetRequest_Call struct {
	*mock.Call
}

// GetRequest is a helper method to define mock.On call
func (_e *MockResizeRequestGetter_Expecter) GetRequest() *MockResizeRequestGetter_GetRequest_Call {
	return &MockResizeRequestGetter_GetRequest_Call{Call: _e.mock.On("GetRequest")}
}

func (_c *MockResizeRequestGetter_GetRequest_Call) Run(run func()) *MockResizeRequestGetter_GetRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResizeRequestGetter_GetRequest_Call) Return(resizeRequest *controller.ResizeRequest, err error) *MockResizeRequestGetter_GetRequest_Call {
	_c.Call.Return(resizeRequest, err)
	return _c
}

func (_c *MockResizeRequestGetter_GetRequest_Call) RunAndReturn(run func() (*controller.ResizeRequest, error)) *MockResizeRequestGetter_GetRequest_Call {
	_c.Call.Return(run)
	return _c
}
