// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controller

import (
	"controller/internal/controller"

	mock "github.com/stretchr/testify/mock"
)

// NewMockResizer creates a new instance of MockResizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResizer {
	mock := &MockResizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResizer is an autogenerated mock type for the Resizer type
type MockResizer struct {
	mock.Mock
}

type MockResizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResizer) EXPECT() *MockResizer_Expecter {
	return &MockResizer_Expecter{mock: &_m.Mock}
}

// AddWorkers provides a mock function for the type MockResizer
func (_mock *MockResizer) AddWorkers(ints []int) error {
	ret := _mock.Called(ints)

	if len(ret) == 0 {
		panic("no return value specified for AddWorkers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]int) error); ok {
		r0 = returnFunc(ints)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockResizer_AddWorkers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWorkers'
type MockResizer_AddWorkers_Call struct {
	*mock.Call
}

// AddWorkers is a helper method to define mock.On call
//   - ints []int
func (_e *MockResizer_Expecter) AddWorkers(ints interface{}) *MockResizer_AddWorkers_Call {
	return &MockResizer_AddWorkers_Call{Call: _e.mock.On("AddWorkers", ints)}
}

func (_c *MockResizer_AddWorkers_Call) Run(run func(ints []int)) *MockResizer_AddWorkers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int
		if args[0] != nil {
			arg0 = args[0].([]int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResizer_AddWorkers_Call) Return(err error) *MockResizer_AddWorkers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockResizer_AddWorkers_Call) RunAndReturn(run func(ints []int) error) *MockResizer_AddWorkers_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWorkers provides a mock function for the type MockResizer
func (_mock *MockResizer) DeleteWorkers(deployedWorkers []controller.DeployedWorker) error {
	ret := _mock.Called(deployedWorkers)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]controller.DeployedWorker) error); ok {
		r0 = returnFunc(deployedWorkers)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockResizer_DeleteWorkers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkers'
type MockResizer_DeleteWorkers_Call struct {
	*mock.Call
}

// DeleteWorkers is a helper method to define mock.On call
//   - deployedWorkers []controller.DeployedWorker
func (_e *MockResizer_Expecter) DeleteWorkers(deployedWorkers interface{}) *MockResizer_DeleteWorkers_Call {
	return &MockResizer_DeleteWorkers_Call{Call: _e.mock.On("DeleteWorkers", deployedWorkers)}
}

func (_c *MockResizer_DeleteWorkers_Call) Run(run func(deployedWorkers []controller.DeployedWorker)) *MockResizer_DeleteWorkers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []controller.DeployedWorker
		if args[0] != nil {
			arg0 = args[0].([]controller.DeployedWorker)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResizer_DeleteWorkers_Call) Return(err error) *MockResizer_DeleteWorkers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockResizer_DeleteWorkers_Call) RunAndReturn(run func(deployedWorkers []controller.DeployedWorker) error) *MockResizer_DeleteWorkers_Call {
	_c.Call.Return(run)
	return _c
}

// GetAndUpdateWorkers provides a mock function for the type MockResizer
func (_mock *MockResizer) GetAndUpdateWorkers() ([]controller.DeployedWorker, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAndUpdateWorkers")
	}

	var r0 []controller.DeployedWorker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]controller.DeployedWorker, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []controller.DeployedWorker); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]controller.DeployedWorker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResizer_GetAndUpdateWorkers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAndUpdateWorkers'
type MockResizer_GetAndUpdateWorkers_Call struct {
	*mock.Call
}

// GetAndUpdateWorkers is a helper method to define mock.On call
func (_e *MockResizer_Expecter) GetAndUpdateWorkers() *MockResizer_GetAndUpdateWorkers_Call {
	return &MockResizer_GetAndUpdateWorkers_Call{Call: _e.mock.On("GetAndUpdateWorkers")}
}

func (_c *MockResizer_GetAndUpdateWorkers_Call) Run(run func()) *MockResizer_GetAndUpdateWorkers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResizer_GetAndUpdateWorkers_Call) Return(deployedWorkers []controller.DeployedWorker, err error) *MockResizer_GetAndUpdateWorkers_Call {
	_c.Call.Return(deployedWorkers, err)
	return _c
}

func (_c *MockResizer_GetAndUpdateWorkers_Call) RunAndReturn(run func() ([]controller.DeployedWorker, error)) *MockResizer_GetAndUpdateWorkers_Call {
	_c.Call.Return(run)
	return _c
}
