// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	request "controller/internal/request"

	mock "github.com/stretchr/testify/mock"
)

// Getter is an autogenerated mock type for the Getter type
type Getter struct {
	mock.Mock
}

type Getter_Expecter struct {
	mock *mock.Mock
}

func (_m *Getter) EXPECT() *Getter_Expecter {
	return &Getter_Expecter{mock: &_m.Mock}
}

// GetRequest provides a mock function with given fields:
func (_m *Getter) GetRequest() (*request.ResizeRequest, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRequest")
	}

	var r0 *request.ResizeRequest
	var r1 error
	if rf, ok := ret.Get(0).(func() (*request.ResizeRequest, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *request.ResizeRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.ResizeRequest)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Getter_GetRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequest'
type Getter_GetRequest_Call struct {
	*mock.Call
}

// GetRequest is a helper method to define mock.On call
func (_e *Getter_Expecter) GetRequest() *Getter_GetRequest_Call {
	return &Getter_GetRequest_Call{Call: _e.mock.On("GetRequest")}
}

func (_c *Getter_GetRequest_Call) Run(run func()) *Getter_GetRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Getter_GetRequest_Call) Return(_a0 *request.ResizeRequest, _a1 error) *Getter_GetRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Getter_GetRequest_Call) RunAndReturn(run func() (*request.ResizeRequest, error)) *Getter_GetRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetter creates a new instance of Getter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Getter {
	mock := &Getter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
