// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package certificate

import (
	"controller/internal/certificate"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCertCreator creates a new instance of MockCertCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCertCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCertCreator {
	mock := &MockCertCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCertCreator is an autogenerated mock type for the CertCreator type
type MockCertCreator struct {
	mock.Mock
}

type MockCertCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCertCreator) EXPECT() *MockCertCreator_Expecter {
	return &MockCertCreator_Expecter{mock: &_m.Mock}
}

// CreateSharedSecret provides a mock function for the type MockCertCreator
func (_mock *MockCertCreator) CreateSharedSecret() (*certificate.SharedSecret, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateSharedSecret")
	}

	var r0 *certificate.SharedSecret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*certificate.SharedSecret, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *certificate.SharedSecret); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certificate.SharedSecret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCertCreator_CreateSharedSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSharedSecret'
type MockCertCreator_CreateSharedSecret_Call struct {
	*mock.Call
}

// CreateSharedSecret is a helper method to define mock.On call
func (_e *MockCertCreator_Expecter) CreateSharedSecret() *MockCertCreator_CreateSharedSecret_Call {
	return &MockCertCreator_CreateSharedSecret_Call{Call: _e.mock.On("CreateSharedSecret")}
}

func (_c *MockCertCreator_CreateSharedSecret_Call) Run(run func()) *MockCertCreator_CreateSharedSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCertCreator_CreateSharedSecret_Call) Return(v *certificate.SharedSecret, err error) *MockCertCreator_CreateSharedSecret_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockCertCreator_CreateSharedSecret_Call) RunAndReturn(run func() (*certificate.SharedSecret, error)) *MockCertCreator_CreateSharedSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateCertificate provides a mock function for the type MockCertCreator
func (_mock *MockCertCreator) GenerateCertificate(v *certificate.SharedSecret) (*certificate.Certificate, error) {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCertificate")
	}

	var r0 *certificate.Certificate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*certificate.SharedSecret) (*certificate.Certificate, error)); ok {
		return returnFunc(v)
	}
	if returnFunc, ok := ret.Get(0).(func(*certificate.SharedSecret) *certificate.Certificate); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certificate.Certificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*certificate.SharedSecret) error); ok {
		r1 = returnFunc(v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCertCreator_GenerateCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCertificate'
type MockCertCreator_GenerateCertificate_Call struct {
	*mock.Call
}

// GenerateCertificate is a helper method to define mock.On call
//   - v *certificate.SharedSecret
func (_e *MockCertCreator_Expecter) GenerateCertificate(v interface{}) *MockCertCreator_GenerateCertificate_Call {
	return &MockCertCreator_GenerateCertificate_Call{Call: _e.mock.On("GenerateCertificate", v)}
}

func (_c *MockCertCreator_GenerateCertificate_Call) Run(run func(v *certificate.SharedSecret)) *MockCertCreator_GenerateCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *certificate.SharedSecret
		if args[0] != nil {
			arg0 = args[0].(*certificate.SharedSecret)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCertCreator_GenerateCertificate_Call) Return(v1 *certificate.Certificate, err error) *MockCertCreator_GenerateCertificate_Call {
	_c.Call.Return(v1, err)
	return _c
}

func (_c *MockCertCreator_GenerateCertificate_Call) RunAndReturn(run func(v *certificate.SharedSecret) (*certificate.Certificate, error)) *MockCertCreator_GenerateCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateCertificateWithHostname provides a mock function for the type MockCertCreator
func (_mock *MockCertCreator) GenerateCertificateWithHostname(v *certificate.SharedSecret, s string) (*certificate.Certificate, error) {
	ret := _mock.Called(v, s)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCertificateWithHostname")
	}

	var r0 *certificate.Certificate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*certificate.SharedSecret, string) (*certificate.Certificate, error)); ok {
		return returnFunc(v, s)
	}
	if returnFunc, ok := ret.Get(0).(func(*certificate.SharedSecret, string) *certificate.Certificate); ok {
		r0 = returnFunc(v, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certificate.Certificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*certificate.SharedSecret, string) error); ok {
		r1 = returnFunc(v, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCertCreator_GenerateCertificateWithHostname_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCertificateWithHostname'
type MockCertCreator_GenerateCertificateWithHostname_Call struct {
	*mock.Call
}

// GenerateCertificateWithHostname is a helper method to define mock.On call
//   - v *certificate.SharedSecret
//   - s string
func (_e *MockCertCreator_Expecter) GenerateCertificateWithHostname(v interface{}, s interface{}) *MockCertCreator_GenerateCertificateWithHostname_Call {
	return &MockCertCreator_GenerateCertificateWithHostname_Call{Call: _e.mock.On("GenerateCertificateWithHostname", v, s)}
}

func (_c *MockCertCreator_GenerateCertificateWithHostname_Call) Run(run func(v *certificate.SharedSecret, s string)) *MockCertCreator_GenerateCertificateWithHostname_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *certificate.SharedSecret
		if args[0] != nil {
			arg0 = args[0].(*certificate.SharedSecret)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCertCreator_GenerateCertificateWithHostname_Call) Return(v1 *certificate.Certificate, err error) *MockCertCreator_GenerateCertificateWithHostname_Call {
	_c.Call.Return(v1, err)
	return _c
}

func (_c *MockCertCreator_GenerateCertificateWithHostname_Call) RunAndReturn(run func(v *certificate.SharedSecret, s string) (*certificate.Certificate, error)) *MockCertCreator_GenerateCertificateWithHostname_Call {
	_c.Call.Return(run)
	return _c
}

// LoadSharedSecret provides a mock function for the type MockCertCreator
func (_mock *MockCertCreator) LoadSharedSecret(bytes []byte) (*certificate.SharedSecret, error) {
	ret := _mock.Called(bytes)

	if len(ret) == 0 {
		panic("no return value specified for LoadSharedSecret")
	}

	var r0 *certificate.SharedSecret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (*certificate.SharedSecret, error)); ok {
		return returnFunc(bytes)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) *certificate.SharedSecret); ok {
		r0 = returnFunc(bytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*certificate.SharedSecret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCertCreator_LoadSharedSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadSharedSecret'
type MockCertCreator_LoadSharedSecret_Call struct {
	*mock.Call
}

// LoadSharedSecret is a helper method to define mock.On call
//   - bytes []byte
func (_e *MockCertCreator_Expecter) LoadSharedSecret(bytes interface{}) *MockCertCreator_LoadSharedSecret_Call {
	return &MockCertCreator_LoadSharedSecret_Call{Call: _e.mock.On("LoadSharedSecret", bytes)}
}

func (_c *MockCertCreator_LoadSharedSecret_Call) Run(run func(bytes []byte)) *MockCertCreator_LoadSharedSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCertCreator_LoadSharedSecret_Call) Return(v *certificate.SharedSecret, err error) *MockCertCreator_LoadSharedSecret_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockCertCreator_LoadSharedSecret_Call) RunAndReturn(run func(bytes []byte) (*certificate.SharedSecret, error)) *MockCertCreator_LoadSharedSecret_Call {
	_c.Call.Return(run)
	return _c
}
