// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resize

import (
	mock "github.com/stretchr/testify/mock"
	"k8s.io/api/apps/v1"
	v10 "k8s.io/api/core/v1"
)

// NewMockSpecFactory creates a new instance of MockSpecFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSpecFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSpecFactory {
	mock := &MockSpecFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSpecFactory is an autogenerated mock type for the SpecFactory type
type MockSpecFactory struct {
	mock.Mock
}

type MockSpecFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSpecFactory) EXPECT() *MockSpecFactory_Expecter {
	return &MockSpecFactory_Expecter{mock: &_m.Mock}
}

// GetPoolProxyDeploymentSpec provides a mock function for the type MockSpecFactory
func (_mock *MockSpecFactory) GetPoolProxyDeploymentSpec(n int) (*v1.Deployment, error) {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for GetPoolProxyDeploymentSpec")
	}

	var r0 *v1.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*v1.Deployment, error)); ok {
		return returnFunc(n)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *v1.Deployment); ok {
		r0 = returnFunc(n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSpecFactory_GetPoolProxyDeploymentSpec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPoolProxyDeploymentSpec'
type MockSpecFactory_GetPoolProxyDeploymentSpec_Call struct {
	*mock.Call
}

// GetPoolProxyDeploymentSpec is a helper method to define mock.On call
//   - n int
func (_e *MockSpecFactory_Expecter) GetPoolProxyDeploymentSpec(n interface{}) *MockSpecFactory_GetPoolProxyDeploymentSpec_Call {
	return &MockSpecFactory_GetPoolProxyDeploymentSpec_Call{Call: _e.mock.On("GetPoolProxyDeploymentSpec", n)}
}

func (_c *MockSpecFactory_GetPoolProxyDeploymentSpec_Call) Run(run func(n int)) *MockSpecFactory_GetPoolProxyDeploymentSpec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSpecFactory_GetPoolProxyDeploymentSpec_Call) Return(deployment *v1.Deployment, err error) *MockSpecFactory_GetPoolProxyDeploymentSpec_Call {
	_c.Call.Return(deployment, err)
	return _c
}

func (_c *MockSpecFactory_GetPoolProxyDeploymentSpec_Call) RunAndReturn(run func(n int) (*v1.Deployment, error)) *MockSpecFactory_GetPoolProxyDeploymentSpec_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkerPodSpec provides a mock function for the type MockSpecFactory
func (_mock *MockSpecFactory) GetWorkerPodSpec(n int) (*v10.Pod, error) {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkerPodSpec")
	}

	var r0 *v10.Pod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*v10.Pod, error)); ok {
		return returnFunc(n)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *v10.Pod); ok {
		r0 = returnFunc(n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.Pod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSpecFactory_GetWorkerPodSpec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkerPodSpec'
type MockSpecFactory_GetWorkerPodSpec_Call struct {
	*mock.Call
}

// GetWorkerPodSpec is a helper method to define mock.On call
//   - n int
func (_e *MockSpecFactory_Expecter) GetWorkerPodSpec(n interface{}) *MockSpecFactory_GetWorkerPodSpec_Call {
	return &MockSpecFactory_GetWorkerPodSpec_Call{Call: _e.mock.On("GetWorkerPodSpec", n)}
}

func (_c *MockSpecFactory_GetWorkerPodSpec_Call) Run(run func(n int)) *MockSpecFactory_GetWorkerPodSpec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSpecFactory_GetWorkerPodSpec_Call) Return(pod *v10.Pod, err error) *MockSpecFactory_GetWorkerPodSpec_Call {
	_c.Call.Return(pod, err)
	return _c
}

func (_c *MockSpecFactory_GetWorkerPodSpec_Call) RunAndReturn(run func(n int) (*v10.Pod, error)) *MockSpecFactory_GetWorkerPodSpec_Call {
	_c.Call.Return(run)
	return _c
}
