// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resize

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTemplateChecker creates a new instance of MockTemplateChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplateChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplateChecker {
	mock := &MockTemplateChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTemplateChecker is an autogenerated mock type for the TemplateChecker type
type MockTemplateChecker struct {
	mock.Mock
}

type MockTemplateChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplateChecker) EXPECT() *MockTemplateChecker_Expecter {
	return &MockTemplateChecker_Expecter{mock: &_m.Mock}
}

// GetPoolProxyTemplateChecksum provides a mock function for the type MockTemplateChecker
func (_mock *MockTemplateChecker) GetPoolProxyTemplateChecksum() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPoolProxyTemplateChecksum")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTemplateChecker_GetPoolProxyTemplateChecksum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPoolProxyTemplateChecksum'
type MockTemplateChecker_GetPoolProxyTemplateChecksum_Call struct {
	*mock.Call
}

// GetPoolProxyTemplateChecksum is a helper method to define mock.On call
func (_e *MockTemplateChecker_Expecter) GetPoolProxyTemplateChecksum() *MockTemplateChecker_GetPoolProxyTemplateChecksum_Call {
	return &MockTemplateChecker_GetPoolProxyTemplateChecksum_Call{Call: _e.mock.On("GetPoolProxyTemplateChecksum")}
}

func (_c *MockTemplateChecker_GetPoolProxyTemplateChecksum_Call) Run(run func()) *MockTemplateChecker_GetPoolProxyTemplateChecksum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTemplateChecker_GetPoolProxyTemplateChecksum_Call) Return(s string) *MockTemplateChecker_GetPoolProxyTemplateChecksum_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTemplateChecker_GetPoolProxyTemplateChecksum_Call) RunAndReturn(run func() string) *MockTemplateChecker_GetPoolProxyTemplateChecksum_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkerTemplateChecksum provides a mock function for the type MockTemplateChecker
func (_mock *MockTemplateChecker) GetWorkerTemplateChecksum() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetWorkerTemplateChecksum")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTemplateChecker_GetWorkerTemplateChecksum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkerTemplateChecksum'
type MockTemplateChecker_GetWorkerTemplateChecksum_Call struct {
	*mock.Call
}

// GetWorkerTemplateChecksum is a helper method to define mock.On call
func (_e *MockTemplateChecker_Expecter) GetWorkerTemplateChecksum() *MockTemplateChecker_GetWorkerTemplateChecksum_Call {
	return &MockTemplateChecker_GetWorkerTemplateChecksum_Call{Call: _e.mock.On("GetWorkerTemplateChecksum")}
}

func (_c *MockTemplateChecker_GetWorkerTemplateChecksum_Call) Run(run func()) *MockTemplateChecker_GetWorkerTemplateChecksum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTemplateChecker_GetWorkerTemplateChecksum_Call) Return(s string) *MockTemplateChecker_GetWorkerTemplateChecksum_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTemplateChecker_GetWorkerTemplateChecksum_Call) RunAndReturn(run func() string) *MockTemplateChecker_GetWorkerTemplateChecksum_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type MockTemplateChecker
func (_mock *MockTemplateChecker) Refresh() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTemplateChecker_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockTemplateChecker_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
func (_e *MockTemplateChecker_Expecter) Refresh() *MockTemplateChecker_Refresh_Call {
	return &MockTemplateChecker_Refresh_Call{Call: _e.mock.On("Refresh")}
}

func (_c *MockTemplateChecker_Refresh_Call) Run(run func()) *MockTemplateChecker_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTemplateChecker_Refresh_Call) Return(err error) *MockTemplateChecker_Refresh_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTemplateChecker_Refresh_Call) RunAndReturn(run func() error) *MockTemplateChecker_Refresh_Call {
	_c.Call.Return(run)
	return _c
}
